### ISSUE TITLE
add button to force schema data refresh

### ISSUE THREAD

**Issue by jweinstein** [wagonhq/feedback#20]

**Comment by srobertson** [comment]
For context:
In our org we create and modify a ton of tables a lot of them automatically. I use wagon to monitor production data changes. It's a pain to have to reconnect to see schema changes when someone else (robot deploy or human) makes a change to the schemas.

**Comment by jweinstein** [comment]
Was talking to @benjamin-wagon, it should be straightforward.

**Comment by grano** [comment]
Duplicate of https://github.com/wagonhq/feedback/issues/15
