### ISSUE TITLE
incorrectly taken to chart tab for results with 0 rows

### ISSUE THREAD

**Issue by grano** [wagonhq/feedback#3]
1. Run `select 1;` and create a chart. Leave the statement card on the chart pane.
2. Run `select 1 limit 0;`. Chart pane should be unelectable

![image](https://cloud.githubusercontent.com/assets/1960182/12631640/4c50f28a-c507-11e5-870e-31c3169cb935.png)

reported by a student during our SQL class

**Comment by mdeland** [comment]
Fixed, should go out on next release
